### PR TITLE
Use Eclipse Oxygen update site. Fixes #1649

### LINKED ISSUE #1649: Prepare RedDeer for oxygen

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by apodhrad** [comment]
Is RedDeer ready for this PR? I mean - Have we adapted the changes made in Oxygen?

**Comment by rawagner** [comment]
This PR was just a test to try if RedDeer works with Oxygen. M6 was ok, but we have issues with M7. Reported https://github.com/eclipse/reddeer/issues/1719

**Comment by eclipsewebmaster** [comment]
testPR

**Comment by genie-reddeer** [comment]
test comment from Jenkins

**Comment by eclipsewebmaster** [comment]
testPR

**Pull request closed without merging**
