### PR TITLE
Create a self-contained p2 repository

### PR DESCRIPTION
**Pull request by apodhrad**
Please follow
https://wiki.eclipse.org/Tycho/eclipse-repository#Creating_a_self-contained_p2_repository

### CODE REVIEW

**Comment by odockal** [comment]
Seems alright. No cert popped up...

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
It passed via old jenkins prcheck job, I do not think it is necessary to wait for new jenkins to merge this pr, @apodhrad @rawagner agreed?

**Comment by rawagner** [comment]
+1

**Pull request merged**
