### PR TITLE
Fixing failing AERI tests #1977

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jkopriva I made some other changes. Let's wait for another build to finish.

**Comment by jkopriva** [comment]
@odockal build is failing due to tycho 1.3.0, see log

**Comment by odockal** [comment]
@jkopriva Hm! That is interesting. Probably I got it built in .m2 repo from somewhere else... Moving back to 1.2.0.

**Comment by odockal** [comment]
@jkopriva Last commit does not include aeri server extension point, so that we can test jenkins job error when there is no test result in concrete module.

**Comment by jkopriva** [comment]
Looks good, merging

**Comment by odockal** [comment]
@jkopriva  Thanks!

**Pull request merged**
