### PR TITLE
Implement adding/removing breakpoints

### PR DESCRIPTION
**Pull request by apodhrad**

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@apodhrad some tests are failing

**Comment by apodhrad** [comment]
Any of the failed tests is not related to this PR

**Comment by apodhrad** [comment]
The problem was that my test didn't clean a workspace and the next test (JUnitRunTest) didn't use
```
@CleanWorkspace
```

**Comment by apodhrad** [comment]
@rawagner Now only Combo and CCombo tests are failing, so the PR is ready to be merged

**Pull request merged**
