### PR TITLE
Fixing run after call in requirement during test failure

### LINKED ISSUE #1847: Requirement.runAfter is not called when test fails

### PR DESCRIPTION
**Pull request by odockal**
Fixes #1847.

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
Add test please

**Comment by odockal** [comment]
@rawagner tests added.

**Comment by odockal** [comment]
@rawagner I rebased once more, there were test failures, but in other tests.

**Comment by odockal** [comment]
@rawagner Dare to take a look? Failed test do not link to changed code...

**Pull request merged**
