### PR TITLE
Adapt to changes made in Oxygen. Fixes #1719

### LINKED ISSUE #1719: Adapt changes made in Oxygen
Devstudio integration tests are using RedDeer 1.2 for testing oxygen builds, but currently it is failing on OpenPerspectiveRequirement. 
Stacktrace:
```
org.jboss.reddeer.requirements.exception.RequirementsLayerException: Unable to fullffill requirement 'Open Perspective'
	at org.jboss.reddeer.requirements.openperspective.OpenPerspectiveRequirement.fulfill(OpenPerspectiveRequirement.java:109)
	at org.jboss.reddeer.junit.internal.requirement.Requirements.fulfill(Requirements.java:105)
	at org.jboss.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:44)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:72)
	at org.jboss.reddeer.junit.internal.runner.statement.RunAfters.evaluate(RunAfters.java:68)
	at org.jboss.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:59)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:153)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:44)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.reddeer.core.exception.CoreLayerException: No matching widget found with Matcher matching when all matchers match: [Widget matcher matching widgets with style: 8, Matcher matching widgets with text that without mnenomic matches: is "OK", Matcher matching widget with the same type as or type extending class org.eclipse.swt.widgets.Button]
class org.eclipse.swt.widgets.Shell with text 'Open Perspective'
	class org.eclipse.swt.widgets.Composite
		class org.eclipse.swt.widgets.Composite
			class org.eclipse.swt.widgets.Table
			class org.eclipse.swt.widgets.Label with text 'Use F2 to display the description for a selected perspective.'
		class org.eclipse.swt.widgets.Composite with label 'Use F2 to display the description for a selected perspective.'
			class org.eclipse.swt.widgets.Button with label 'Use F2 to display the description for a selected perspective.' with text 'Cancel'
			class org.eclipse.swt.widgets.Button with label 'Use F2 to display the description for a selected perspective.' with text '&Open'
```
Before oxygen, the affirmative button was "Ok", now it is "Open"

### PR DESCRIPTION
**Pull request by rawagner**
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@apodhrad can you take a look ? failed swt tests are bugs in Oxygen and failed ServerTest is present in reddeer regardless of this PR. See issue https://github.com/eclipse/reddeer/issues/1748

**Comment by apodhrad** [comment]
pushed to master

**Pull request closed without merging**
