### PR TITLE
Adding tests for waits

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
Fixes #1616.

**Comment by odockal** [comment]
@rawagner please note failed test. It might be bug in code instead of failure in test itself, wdyt?

**Comment by rawagner** [comment]
@odockal It is quite a corner case :) Do you dare to add check to GroupWait for nulls ?

**Comment by odockal** [comment]
@rawagner true that... but still, it is there... :)

**Pull request merged**
