### PR TITLE
Upversion to 2.3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by odockal**
#1938 
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@rawagner Seems like test failures are not related to changes.

**Comment by rawagner** [comment]
@odockal correct, those tests have been failing for a while.

**Comment by odockal** [comment]
@rawagner  I created new issue aiming those failures introduced in simrel 2018-09:https://github.com/eclipse/reddeer/issues/1942

**Comment by rawagner** [comment]
LGTM

**Pull request merged**
