### PR TITLE
Update RedDeer test plugin to use Java 1.8

### LINKED ISSUE #1993: Reddeer wizard creates a test plug-in with BREE of 1.8 but adds Java 1.5 to classpath
See screenshot, if I use the test plug-in wizard the classpath is not the same as the BREE.

reddeer

### PR DESCRIPTION
**Pull request by odockal**
Fixes #1993 

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
@odockal please review failing tests, thank you!

**Comment by odockal** [comment]
Seems like some glitch.

**Comment by odockal** [comment]
TestPR

**Comment by odockal** [comment]
TestPR

**Comment by jkopriva** [comment]
testPR

**Comment by odockal** [comment]
@jkopriva will we merge this?

**Pull request merged**
