### PR TITLE
Fixes regex matcher failures during finding widgets (fixes #1841)

### LINKED ISSUE #1841: Widget lookup with regexp matchers fails to find widgets containing string with special regexp characters
1. Create server adapter with name "CDK 3.2+" (regular name)
2. Try to get the server item in test via ServersView.getServer("CDK 3.2+")
"+" character is the problem here. But I believe that even the dot could cause some troubles. All such characters should be prefixed with "\\" in regexp.

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by genie-reddeer** [comment]
Can one of the admins verify this patch?

**Comment by odockal** [comment]
testPR

**Comment by rawagner** [comment]
testPR

**Comment by odockal** [comment]
@rawagner Strange that prcheck job was triggered after your comment, not mine...

**Comment by jkopriva** [comment]
@rawagner thx for merging :)

**Comment by rawagner** [comment]
sure, thx for the fix! :)

**Pull request merged**
