### PR TITLE
Make it possible to run only test method in test (fixes #1788)

### LINKED ISSUE #1788: Cannot execute one specific test from IDE
If you specify a test method in a run configuration in Eclipse IDE then you will get
```
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=testFoo2 fuse-630R4.json], {ExactMatcher:fDisplayName=testFoo2 fuse-630R4.json(org.jboss.tools.fuse.qe.reddeer.tests.FooTest)]] from org.junit.internal.requests.ClassRequest@7847a87f
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:77)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:68)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@apodhrad Would you test this patch on your cases where running of one test method was broken? Thanks

**Comment by apodhrad** [comment]
@odockal Have you tried it with a requirement?
I'm getting initialization error :(

**Comment by odockal** [comment]
@apodhrad I do not recall. Will give it a try!

**Comment by apodhrad** [comment]
```
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=atomBindingTest switchyard.yaml], {ExactMatcher:fDisplayName=atomBindingTest switchyard.yaml(org.jboss.tools.switchyard.ui.bot.test.SwitchYardEditorBindingsTest)]] from org.junit.internal.requests.ClassRequest@46ff93c3
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:80)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:71)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:523)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by odockal** [comment]
@apodhrad I tried to run all requirements tests locally and got no error...

**Comment by apodhrad** [comment]
If you execute test ServerPresentTest#isServerPresentTest then you will get the following error
```
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=isServerPresentTest requirements.json], {ExactMatcher:fDisplayName=isServerPresentTest requirements.json(org.eclipse.reddeer.requirements.test.server.ServerPresentTest)]] from org.junit.internal.requests.ClassRequest@42088b35
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:80)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:71)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:523)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)

**Comment by odockal** [comment]
@apodhrad Seems to be partially solved. But some other problems occured as with change of test class to run, JUnit editor shows tests under unrooted suite. Or how to call it properly. Needs to be dealt in RedDeerSuite somewhere.

**Pull request merged**
