### PR TITLE
Reset perspective fails with Eclipse Platform 4.8 I-builds

### PR DESCRIPTION
**Pull request by akurtakov**
Test for Reset Perspective button instead of Yes for Photon changes.

Signed-off-by: Alexander Kurtakov <akurtako@redhat.com>

### CODE REVIEW

**Comment by akurtakov** [comment]
Should fix #1880

**Comment by genie-reddeer** [comment]
Can one of the admins verify this patch?

**Comment by odockal** [comment]
testPR

**Comment by akurtakov** [comment]
Is there smth wrong with the CI ? I can not access it seeing that hudson is down? Are tests not run at all?

**Comment by rawagner** [comment]
CI is down and I cannot even start/restart. Bug is here https://bugs.eclipse.org/bugs/show_bug.cgi?id=530435

**Pull request merged**
