### PR TITLE
issue #2066: remove AERI dependency.

### LINKED ISSUE #2066: Removed deprecated AERI extension
Hi,

it seems AERI is not used anymore nor maintained. It causes some problems as it cannot start :
osgi> ss aeri
"Framework is launched."
id	State       Bundle
323	STARTING    org.eclipse.epp.logging.aeri.core_2.0.7.v20180504-0806
324	INSTALLED   org.eclipse.epp.logging.aeri.ide_2.0.7.v20180504-0806
osgi> start 324
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.epp.logging.aeri.ide [324]
  Unresolved requirement: Import-Package: org.apache.lucene.document; version="[7.1.0,8.0.0)"

So i suggest to simply remove it from reddeer. Is it still used here?

### PR DESCRIPTION
**Pull request by sbouchet**
Change-Id: I2d194cbb53880d848485447b780e3c7df5dcec18
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

# Pull Request Checklist

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?
* Is copyright with correct year in new files?
* Is there a JavaDoc in every class with description of a class and an author(and issue if suitable)?
* Is there a link to github project issue? (if needed)

fixes #2066 

## Testing
* Does it work?
* Are the tests green on Jenkins? Is there a link to Jenkins build?

### CODE REVIEW

**Comment by genie-reddeer** [comment]
Can one of the admins verify this patch?

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@sbouchet Could you please rebase this PR? I have upversioned and would like to see how this PR will go.. Thanks!

**Comment by odockal** [comment]
testPR

**Pull request merged**
