### PR TITLE
Adding swtbot dependecies into update site #1792

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@rawagner @apodhrad I am not pretty sure about this, could you please check it out, and eventually give an advice if this is alright and how this could be tested? in case that I should also remove actual swtbot dependencies from manifests, please, do tell me. Thanks!

**Comment by rawagner** [comment]
@odockal build the update site locally (simple mvn clean verify on reddeer parent pom), site will be in target folder. Add the site to eclipse and try to install generator/recorder plugins. Make sure that no other sites that may contain swtbot are not defined

**Comment by odockal** [comment]
@rawagner Thanks! So, I did run mvn clean verify and checked that site/target directory contained repository with swtbot features, and in IDE it was possible to install reddeer codegen that brought swtbot.generator feature with it. Seems fine than.

**Comment by apodhrad** [comment]
I'm getting the following pop up
eclipse_reddeer_cert

**Comment by apodhrad** [comment]
It will be fixed in #1803

**Comment by apodhrad** [comment]
fixed by #1803

**Pull request closed without merging**
