### PR TITLE
Prepare oxygen target platform

### PR DESCRIPTION
**Pull request by apodhrad**

### CODE REVIEW

**Comment by apodhrad** [comment]
Now, we can easily switch between neon and oxygen

**Comment by apodhrad** [comment]
Need to add aeri dependencies

**Comment by apodhrad** [comment]
Done.

**Comment by apodhrad** [comment]
Argh... there are still some missing dependencies :(

**Comment by apodhrad** [comment]
It should be ok now

**Comment by apodhrad** [comment]
oh.. the aeri deps completely broke the tp :(

**Comment by rawagner** [comment]
is this ready ?

**Comment by apodhrad** [comment]
yes, it is ready now

**Pull request merged**
