### PR TITLE
Updating orbit update site for 2018-12 RC1

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Comment by odockal** [comment]
@jkopriva ready to be merged?

**Comment by odockal** [comment]
@jkopriva I have built this Pr locally and installed it into Eclipse. everything went fine.

**Comment by jkopriva** [comment]
LGTM, merging.

**Pull request merged**
