### PR TITLE
Upversioning to 2.3.0.Final

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@rawagner Any idea why is archetype test step failing? Ref: https://hudson.eclipse.org/reddeer/job/reddeer.prcheck.photon/102/consol, even though this is photon based build, the same came from 2018-09 rel.

**Comment by rawagner** [comment]
There's a lot of exceptions in log from eclipse started by archetype tests. See https://hudson.eclipse.org/reddeer/job/reddeer.prcheck.photon/ws/archetype/target/test-classes/projects/eclipse-reddeer-archetype/project/2018-09/target/work/data/.metadata/.log

Archetype tests are using 2018-09 build even in photon verification see https://github.com/eclipse/reddeer/blob/master/archetype/src/main/resources/archetype-resources/pom.xml#L36 so the issue is with 2018-09 build..maybe some dependency is missing..

**Comment by odockal** [comment]
@rawagner Yes, I know about it, although I do not know that to do with it. I am going to try to run it in IDE and see if I can narrow the places where it can fails.

**Comment by odockal** [comment]
@rawagner @jkopriva  I have changed the test archetype project to be run against photon release + reddeer 2.2.0 to pass all the test. As we do not have right to maven repo to have actual archetype available to broader audience, I am ok with having this archetype aimed to photon and fix the issue in next release as we are having RC2 +3 today and I did not make it run today.

**Comment by odockal** [comment]
Builds are green. Merging.

**Pull request merged**
