### PR TITLE
Create an initial target platform for RedDeer development

### PR DESCRIPTION
**Pull request by apodhrad**

### CODE REVIEW

**Comment by apodhrad** [comment]
There is an issue related to #1722

**Comment by apodhrad** [comment]
I've added the missing m2e dependency and it should be ok now.

**Comment by apodhrad** [comment]
Added sign-off

**Comment by rawagner** [comment]
please add licence info to the xml file

**Comment by apodhrad** [comment]
Unfortunately, Eclipse IDE removes all comments in that XML file if you open it via IDE :( And we want to open it via IDE and set the TP.

I think it's not necessary to include license info (neither jbosstools does it).

**Pull request merged**
