### PR TITLE
AbstractExplorer can have links instead of tree (fixes #2003)

### LINKED ISSUE #2003: AbtractExplorer is relying on having a Tree which is no more the case when there is no project
Due to this new feature, https://www.eclipse.org/eclipse/news/4.11/platform.php#onboarding-text
Trying to retrieve the list of projects is failing with latest Eclipse version.
The code is still making the assumption that there is always a Tree available https://github.com/eclipse/reddeer/blob/36c8d1287bfde604606e50bd7ac2945f9171c714/plugins/org.eclipse.reddeer.eclipse/src/org/eclipse/reddeer/eclipse/ui/navigator/resources/AbstractExplorer.java#L109

example of error stack:
```org.eclipse.reddeer.core.exception.CoreLayerException: No matching widget found with Matcher matching when all matchers match: [Matcher matching widget with the same type as or type extending class org.eclipse.swt.widgets.Tree]
class org.eclipse.swt.widgets.Composite[shell: 'data']
	class org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1[shell: 'data']
		class org.eclipse.swt.widgets.Composite[shell: 'data']
			class org.eclipse.swt.widgets.Composite[shell: 'data']
				class org.eclipse.swt.widgets.Tree[shell: 'data']
				class org.eclipse.swt.widgets.Composite[shell: 'data']
					class org.eclipse.swt.widgets.Composite[shell: 'data']
						class org.eclipse.swt.widgets.Link[shell: 'data'] with text 'There are no projects in your workspace.
To add a project:'
						class org.eclipse.swt.widgets.Composite[shell: 'data']
							class org.eclipse.swt.widgets.Label[shell: 'data'] with text ''
							class org.eclipse.ui.forms.widgets.Hyperlink[shell: 'data'] with text 'Create a Java project'
							class org.eclipse.swt.widgets.Label[shell: 'data'] with text ''
							class org.eclipse.ui.forms.widgets.Hyperlink[shell: 'data'] with text 'Create a project...'
							class org.eclipse.swt.widgets.Label[shell: 'data'] with text ''
							class org.eclipse.ui.forms.widgets.Hyperlink[shell: 'data'] with text 'Import projects...'

	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:114)
	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:87)
	at org.eclipse.reddeer.swt.widgets.AbstractWidget.<init>(AbstractWidget.java:76)
	at org.eclipse.reddeer.swt.widgets.AbstractControl.<init>(AbstractControl.java:38)
	at org.eclipse.reddeer.swt.impl.tree.AbstractTree.<init>(AbstractTree.java:34)
	at org.eclipse.reddeer.swt.impl.tree.DefaultTree.<init>(DefaultTree.java:81)
	at org.eclipse.reddeer.swt.impl.tree.DefaultTree.<init>(DefaultTree.java:41)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.getTree(AbstractExplorer.java:171)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.getProjects(AbstractExplorer.java:109)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.deleteAllProjects(AbstractExplorer.java:157)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.deleteAllProjects(AbstractExplorer.java:145)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.deleteAllProjects(AbstractExplorer.java:136)
	at org.eclipse.reddeer.requirements.cleanworkspace.CleanWorkspaceRequirement.fulfill(CleanWorkspaceRequirement.java:73)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.runSafely(Requirements.java:110)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.lambda$6(Requirements.java:105)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.runSafely(Requirements.java:105)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.fulfill(Requirements.java:76)
	at org.eclipse.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:72)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunAfterClasses.evaluate(RunAfterClasses.java:68)
	at org.eclipse.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:45)
	at org.eclipse.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:57)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)```

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jkopriva I have pushed some tests and fixes to places that appeared to fail. If tests PR check job will end up better now, I would merge this and continue in releasing RC2 bits.

**Comment by jkopriva** [comment]
LGTM - lets wait for Jenkins

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jkopriva Last build ended up with sigsegv from java. I am rerunning it now, it fixed one failing test, others are probably just unstable tests.I make them all pass locally. Let's have this last build and if no serious issues appear I would merge the PR.

**Comment by odockal** [comment]
@jkopriva PR check is green, I am going to merge the PR and proceed with releasing RC2 bits.

**Pull request merged**
