### PR TITLE
Remove requirement on beanutils bundle.

### PR DESCRIPTION
**Pull request by mbooth101**
Usage of beanutils was removed in e81f31b but mention of it still
remains in the manifest. This change removes the "require-bundle"
on beanutils from the manifest.

Signed-off-by: Mat Booth <mat.booth@redhat.com>

### CODE REVIEW

**Comment by genie-reddeer** [comment]
Can one of the admins verify this patch?

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@rawagner Any idea why reddeer.prcheck job was not started for this pr?

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@odockal no idea, but worked for me..

**Comment by rawagner** [comment]
@mbooth101 thanks!

**Pull request merged**
